### PR TITLE
fixed Social login #245

### LINKED ISSUE #245: Social Auth not working
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Login through google/facebook should work

# Current Behavior

Login through google/facebook throws an error

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add required keys to env file
2. Try to log in through facebook/google

### PR DESCRIPTION
**Pull request by kartikpandey2**
Please provide enough information so that others can review your pull request:

- Fixed googeContainer component earlier request was not sent to the server and added toast in case of failure
- Fixed facebookContainer component earlier request was not sent to the server
- Fixed backend logic for social auth and small errors.

**Closing issues**

closes #245

### CODE REVIEW

File: fact-bounty-client/src/shared/OAuthContainer/FacebookContainer.js [hunk 1]
```diff
@@ -15,13 +17,14 @@ class FacebookContainer extends React.Component {
   }
 
   responseFacebook = res => {
+    console.log(res);
```
[the remark this answers is not in the document]
Comment (kartikpandey2) [reply fact-bounty-client/src/shared/OAuthContainer/FacebookContainer.js]: @Tushar19varshney Done. Also can you write migration for [this](https://github.com/scorelab/fact-Bounty/pull/219/files#diff-ea82e5e1b60fc5fcc95a9f383f904263L24) change in pull request #219. Presently new user entry from social login is not being saved in the database because the password cannot be empty.

File: fact-bounty-client/src/shared/OAuthContainer/index.js [hunk 2]
```diff
@@ -1,38 +1,14 @@
 import React from "react";
 
+import FacebookContainer from "./FacebookContainer";
+import GoogleContainer from "./GoogleContainer";
 import "./index.css";
 
-class OauthContainer extends React.Component {
```
Comment (Anmolbansal1) [inline fact-bounty-client/src/shared/OAuthContainer/index.js]: These were allowing this OAuth container to load asynchronously, which would other components to mount first. It would allow register page to load first

Comment (kartikpandey2) [reply fact-bounty-client/src/shared/OAuthContainer/index.js]: @Anmolbansal1 Yes I know Oauth component was importing google and facebook container asynchronously but I feel It was not worth it because.
-  As there was 2 continuous await statement which might neutralize time saved by asynchronously loading (to improve this we can use Promise.all).
-  Moreover, Google and facebook container components are not so heavy so asynchronously loading will not have any significant impact. 
- Asynchronous loading also made Oauth a complex component.

So I decided to changed it into simple function component 😃
