### PR TITLE
jwt_token error resolved and err.response checks included in action

### LINKED ISSUE #194: dispatching auth action found undefined error and token variable error
Found 2 issues in authentication:

**1.** On clicking the `Login` button faced an error:
Screenshot from 2019-03-19 03-55-35

**Steps to reproduce this error:**
- Insert your registered email and password
- Click on the login button

It can be solved by writing a check for `err.reponse`

**2.**
```js
const { token } = res.data;
```
Above code is not correct as it should be like this:
```js
const token = res.data.access_token
```

I am working on it and will make a PR.

**Thanks**

### PR DESCRIPTION
**Pull request by Tushar19varshney**
@root5533 @ivantha 
Resolved two errors in the authentication code 
**1.** Added check for `err.response` 
**2.** `token` varialble declaration and wrongly assigned bug fixed as
```js 
const token = res.data.access_token 
```
Fixes #194

### CODE REVIEW

File: fact-bounty-client/src/pages/login/actions/authActions.js [hunk 1]
```diff
@@ -26,10 +26,12 @@ export const loginUser = userData => dispatch => {
...
       });
     })
-    .catch(err =>
-      dispatch({
-        type: GET_ERRORS,
-        payload: err.response.data
-      })
-    );
+    .catch(err => {
+      if (err && err.response) {
```
Comment (kartikpandey2) [inline fact-bounty-client/src/pages/login/actions/authActions.js]: hi @Tushar19varshney, I don't think we need the check for this, as `err` and `err.response` will always be true I guess.

Comment (Tushar19varshney) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @kartikpandey2
Have a look at this:
Screenshot from 2019-03-19 21-58-51

In this error comes as data of undefined that means that response is not defined, so that's why I have put the null checks so that code will not breaks.
I hope you get the point :slightly_smiling_face:

**Comment by Tushar19varshney** [comment]
@ivantha Please review!
**Thanks** :slightly_smiling_face:

File: fact-bounty-client/src/pages/login/actions/authActions.js (hunk 1 above)
Comment (kartikpandey2) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @Tushar19varshney  ok, but how shall I reproduce this error and this error is using node server or flask server in backend.?

Comment (Tushar19varshney) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @kartikpandey2 I have mentioned the steps in issue #194 and I am using backend server as we are going to shift our backend to Flask

Comment (kartikpandey2) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @Tushar19varshney I was able reproduce the error and found the error is thrown because of a change in the server response, earlier jwt token field name was `token` now it is `access_token`. I believe it will be better if we try to replicate the `nodejs server response convention and variables name also in flask server`. As this will prevent frontend from breaking and making extra changes to fix the problems which will be arising due to change in response. 

Also, I recommend it will be better if you can replace 
`if(err && err.response)` with 
```
if(err.response || err.request) {
let payload = err.request || err.response.data;
      if (typeof payload === "string") {
        payload = { fetch: payload };
      }
    "dispatch action"
}
```
This consider your case and It will also fix 1 case which I was not able to think( i.e `When server hangs up and don't reply`). You can also refer [Error Handling in axios](https://github.com/axios/axios#handling-error) 😃

Comment (Tushar19varshney) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: Why are you equating `err.request` to the payload because `err.request` is in format like:
Screenshot from 2019-03-20 01-50-44
and Why we are checking for `err.request` ?

Comment (Tushar19varshney) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: As you have also mentioned the check of `err.response`, I think it `if(err&&err.response)` would not break as such :slightly_smiling_face:

Comment (kartikpandey2) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @Tushar19varshney  we are checking for `err.request` just to handle the error due to no response from the server.
I am setting payload = err.request because error 

- Should be object otherwise PropTypes will throw error 
- And error.request is an instance of XHR request and may help will debugging(Just to be in safe side) 😃

Comment (Tushar19varshney) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: I think that setting the whole `request` as a payload is not standard as we are only interested in the error message:sweat_smile: and if we are implementing that if `response` is not coming from the server then the payload is equal to `request` then it should be like this:
```js
let payload

if(err && err.response){
    payload = err.response.data
    if(typeof payload == 'string'){
        payload = { message: payload }
    }
}
else{
     payload = err.request.responseText
     if(typeof payload == 'string'){
         payload = { message: payload }
     }
}
dispatch action
}
```

Comment (kartikpandey2) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @Tushar19varshney  this too makes sense 😃 Implement this way then.

Comment (Tushar19varshney) [reply fact-bounty-client/src/pages/login/actions/authActions.js]: @kartikpandey2 Cool I will soon update my PR :+1:

**Comment by Tushar19varshney** [comment]
@ivantha @Anmolbansal1 Done!
